{
  "openapi": "3.0.0",
  "info": {
    "title": "API Pense Bem",
    "version": "1.0.0",
    "description": "API responsible for delivering books from the Pense Bem project, validating answers to questions, and receiving responses to those questions."
  },
  "servers": [
    {
      "url": "http://localhost:4000",
      "description": "Local Server"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "summary": "Welcome message for the API",
        "responses": {
          "200": {
            "description": "Successfully returned the welcome message"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/book/list": {
      "get": {
        "summary": "Retrieve a list of all books",
        "responses": {
          "200": {
            "description": "Successfully retrieved the list of books",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "books": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string",
                            "default": "animals"
                          },
                          "title": {
                            "type": "integer",
                            "default": "Animals"
                          },
                          "author": {
                            "type": "integer",
                            "default": "Tectoy"
                          },
                          "publisher": {
                            "type": "integer",
                            "default": "Nova Cultural"
                          },
                          "year": {
                            "type": "integer",
                            "default": 1987
                          },
                          "edition": {
                            "type": "integer",
                            "default": 27
                          },
                          "pages": {
                            "type": "integer",
                            "default": 36
                          }
                        }
                      }
                    },
                    "quantity": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "books": [
                    {
                      "id": "animals",
                      "title": "Animals",
                      "author": "Tectoy",
                      "publisher": "Nova Cultural",
                      "year": 1987,
                      "edition": 27,
                      "pages": 36
                    }
                  ],
                  "quantity": 1
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "statusCode": 500,
                  "message": "Erro interno do servidor",
                  "details": null
                }
              }
            }
          }
        }
      }
    },
    "/book/{id}/program/list": {
      "get": {
        "summary": "Retrieve a book programs by its ID",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The unique identifier of the book"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved the book details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "programs": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "programId": {
                            "type": "string"
                          },
                          "quantity": {
                            "type": "integer"
                          }
                        }
                      }
                    },
                    "quantity": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "programs": [
                    {
                      "programId": "091",
                      "quantity": 30
                    },
                    {
                      "programId": "092",
                      "quantity": 30
                    }
                  ],
                  "quantity": 2
                }
              }
            }
          },
          "404": {
            "description": "Program not found for the book",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "statusCode": 404,
                  "message": "Programs not found for the book",
                  "details": null
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "statusCode": 500,
                  "message": "Erro interno do servidor",
                  "details": null
                }
              }
            }
          }
        }
      }
    },    
    "/validate": {
      "post": {
        "summary": "Validate the answer to a question",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "bookId": {
                    "type": "string",
                    "default": "animals"
                  },
                  "programId": {
                    "type": "string",
                    "default": "091"
                  },
                  "question": {
                    "type": "number",
                    "default": 5
                  },
                  "answer": {
                    "type": "string",
                    "default": "B"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully validated the answer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "correct": {
                      "type": "boolean"
                    }
                  }
                },
                "example": {
                  "correct": true
                }
              }
            }
          },
          "404": {
            "description": "Question not found for the program",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "statusCode": 404,
                  "message": "Program XXX not found for the book XXXXXXX",
                  "details": null
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusCode": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "statusCode": 500,
                  "message": "Erro interno do servidor",
                  "details": null
                }
              }
            }
          }
        }
      }
    },
    "/calculate": {
      "get": {
        "summary": "Perform a calculation",
        "responses": {
          "200": {
            "description": "Successfully performed the calculation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    } 
  },
  "components": {
    "schemas": {
      "Book": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "publishedDate": {
            "type": "string",
            "format": "date"
          }
        }
      }
    }
  }
}
